### PR TITLE
Added EOL detection

### LINKED ISSUE #24: LF CRLF problem
When using your module both on Unix and Windows It changes EOL separator every time. Can you maybe set EOL based on project files EOL, not on default OS EOL.

### PR DESCRIPTION
**Pull request by alexeychikk**
Resolves #24

### CODE REVIEW

**Comment by baob** [comment]
Looking forward to the merge and release ;)

**Comment by skovhus** [comment]
Sorry for stalling on this one! @baob thanks for the reminder.

**Comment by skovhus** [comment]
@alexeychikk thanks for contributing!

**Comment by skovhus** [comment]
This was released as version 1.2.0. Please give it a spin :)

**Pull request merged**
